### ISSUE TITLE
error: attributes are not yet allowed on `if` expressions

### ISSUE THREAD

**Issue by Harshil-Jani** [harryfei/which-rs#67]
The `which` crate is causing the CI pipeline to fail due to attributes on `if` expressions.
Eg :
![image](https://user-images.githubusercontent.com/79367883/216461881-a478ccf0-30fd-4430-87ef-f2e709ec7a0c.png)

**Comment by apoelstra** [comment]
cc https://github.com/harryfei/which-rs/pull/62 where I made a note about this.

It's easy enough to work around with `cargo update -p --precise` but if y'all don't mind moving your code around a bit, that's even easier :)

**Comment by Xaeroxe** [comment]
`which` does not have an MSRV policy. I'm not @harryfei therefore I don't have absolute authority over this, but I am a maintainer on this project.

In my opinion, asking downstream to use Rust 1.43 or later is not that big of an ask, as that version is now roughly three years old.

MSRVs mostly exist in order to support old compilers that are actively being distributed by package vendors. Thing is even Debian, a very conservative package vendor, is distributing version 1.63. My suggestion would be that it's time to raise your MSRV. I doubt many users will be impacted by this.

**Comment by apoelstra** [comment]
That's reasonable. We are overdue to increase our MSRV actually, even by our own very conservative policy. But we generally don't actually increase it until something "forces" us to (and actually I think something related to no-std support *has* forced us .... but in additon to being forced we need time :)).

I think for right now we'll just add another `cargo update --precise` line to our README and CI scripts.

**Comment by harryfei** [comment]
Yeah, I agree that Rust 1.43 is too old. So I decide to not find a way to fix this issue.
Next time, I will release which-rs as a break change version if the MSRV is changed.
